language: node_js
node_js:
  - 11
cache:
  # Caches $HOME/.npm when npm ci is default script command
  # Caches node_modules in all other cases
  npm: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache

install:
  - npm ci

before_script:
  ## runs the 'start' script which
  ## boots our local app server on port 3000
  ## which cypress expects to be running
  ## -----------------------------------
  ## the '-- --silent' passes arguments
  ## to http-server which silences its output
  ## else our travis logs would be cluttered
  ## with output from HTTP requests
  ## https://docs.npmjs.com/cli/start
  ## https://github.com/indexzero/http-server
  ## ---------------------------------------
  ## we use the '&' ampersand which tells
  ## travis to run this process in the background
  ## else it would block execution and hang travis
  - npx db-migrate up -env dev --config './db/database.json' -m './db/migrations/'
  - npm run travis-ci --silent &
script:
  - $(npm bin)/cypress run --record --key dba52a70-a752-4120-9f56-37b84c8ecc9f