language: node.js
node_js:
  -"11.11.0"
cache:
directories:
  - node_modules

before_script:
  - npm run prod &
  
script:
  # run unit tests:
 
  # run E2E tests:
  - ./node_modules/.bin/cypress run --record